web:
  - name: backend
    buildCommand: npm install
    startCommand: npm start
    env: .env
    routes:
      - path: "/*"
        method: GET
        command: "npm start"
        services:
          - name: mongodb
            type: mongodb
    automaticDeploys:
      branch: main
